# Generated by Django 5.1.1 on 2025-03-25 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('mass', models.FloatField(default=0, verbose_name='Масса')),
                ('callories_per_100_gram', models.FloatField(default=0, verbose_name='Калории на 100 грамм блюда')),
                ('proteins', models.FloatField(default=0, verbose_name='Белки')),
                ('fats', models.FloatField(default=0, verbose_name='Жиры')),
                ('carbs', models.FloatField(default=0, verbose_name='Углеводы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('callories_per_100_gram', models.FloatField(default=0, verbose_name='Калории на 100 грамм блюда')),
                ('proteins', models.FloatField(default=0, verbose_name='Белки')),
                ('fats', models.FloatField(default=0, verbose_name='Жиры')),
                ('carbs', models.FloatField(default=0, verbose_name='Углеводы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
