# Generated by Django 5.1.1 on 2025-03-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meal_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата-время'),
        ),
    ]
