# Generated by Django 5.1.1 on 2025-03-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_meal_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_calories_per_day',
            field=models.FloatField(default=0, verbose_name='Максимум калорий в день'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_carbs_per_day',
            field=models.FloatField(default=0, verbose_name='Максимум углеводов в день'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_fats_per_day',
            field=models.FloatField(default=0, verbose_name='Максимум жиров в день'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_proteins_per_day',
            field=models.FloatField(default=0, verbose_name='Максимум белков в день'),
        ),
    ]
