# Generated by Django 5.1.1 on 2025-03-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_max_calories_per_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='callories_per_100_gram',
            new_name='calories_per_100_gram',
        ),
    ]
