# Generated by Django 5.1.1 on 2025-03-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_callories_per_100_gram_meal_calories_per_100_gram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='calories_per_100_gram',
            new_name='calories_per_100_gramm',
        ),
    ]
